### ISSUE TITLE
introduced alias handling breaks grape-swagger

### ISSUE THREAD

**Issue by LeFnord** [ruby-grape/grape-swagger-representable#10]
see: https://travis-ci.org/ruby-grape/grape-swagger/jobs/354671566

**Comment by jpsikorra** [comment]
So afaik this fails on the `items` property in the `UseResponse` model in the spec. The property is defined here:
[grape-swagger spec/support/model_parsers/representable_parser.rb#L149](https://github.com/ruby-grape/grape-swagger/blob/46dffa3d287d736a723db86f1bdefeee6bbb70eb/spec/support/model_parsers/representable_parser.rb#L149)

I was wondering whether the expected result (see e.g. [grape-swagger spec/support/model_parsers/representable_parser.rb#L214](https://github.com/ruby-grape/grape-swagger/blob/46dffa3d287d736a723db86f1bdefeee6bbb70eb/spec/support/model_parsers/representable_parser.rb#L214)) is correct, since `items` is aliased to `$responses` and so `$responses` should show up in the swagger-doc and not `items`.

Maybe you could explain it to me?

**Comment by LeFnord** [comment]
thanks for spotting it out, it seems, that the introduced handling is correct, but not the one from grape-swagger

**Comment by kzaitsev** [comment]
@LeFnord looks like you already fix it, and sorry for this, thank you.
